### ISSUE TITLE
iview的button按钮点击做的模态对话框调用formList貌似渲染不出来

### ISSUE THREAD

**Issue by sanny1982** [viewweiwu/iview-form#10]
iview的button按钮点击做的模态对话框调用formList貌似渲染不出来
  import iViewForm from 'iview-form'
  export default {
    name: 'devlist',
    components: {
      Tables,
      iViewForm
    },

----------------------
                   on: {
                      click: () => {
                        this.$Modal.confirm({
                          render: (h) => {
                            return h('div',[
                              h('i-switch',{
                                 props:{
                                   value:true      
                                 }}),
                              h('iview-form',{  //这里替替换成iViewForm也试了，没渲染出来呢
                                props: {
                                  formList: [
                                    {
                                      title: '输入框',
                                      type: 'input'
                                    }
                                  ]
                                }
                              }),
                            ])

![image](https://user-images.githubusercontent.com/40729578/45254359-747d1700-b3a9-11e8-8698-dab5c3eccdd3.png)

**Comment by viewweiwu** [comment]
你有 qq 或者微信吗，我帮你看看

**Comment by sanny1982** [comment]
现在换了一种方式，不直接在模态对话框里熏染了，也达到了一样的效果，谢谢，这个开源组件真的很方便，我的微信xlm1112111
