### ISSUE TITLE
select类型绑定不了事件

### ISSUE THREAD

**Issue by hitfzg** [viewweiwu/iview-form#11]
select组件绑定事件都不生效，不知道是写法问题，还是不支持
![image](https://user-images.githubusercontent.com/8349973/45398146-9f02f480-b675-11e8-89ad-09fb70152900.png)

**Comment by viewweiwu** [comment]
iview 组件库需要监听 on-change 前面有个 ’on-‘，element-ui 才是 change 事件

      on: {
        'on-change': (value) => {
          console.log(value)
        }
      }
