### ISSUE TITLE
formlist中类型是select的options动态渲染

### ISSUE THREAD

**Issue by Sunyip2017** [viewweiwu/iview-form#13]
` clothList:[],
      insertForm: [
        {
          type:'select',
          title: '品类',
          key: 'clothname',
          options:this.clothList
     },`

这样为啥表单就不渲染了，动态数据如何渲染？

**Comment by viewweiwu** [comment]
虽然不推荐，不过你可以尝试把  formList 放进 computed 里面

**Comment by Sunyip2017** [comment]
使用renderContent可以解决这个问题，已亲测
