### ISSUE TITLE
ie下无法使用

### ISSUE THREAD

**Issue by weihuan1** [viewweiwu/iview-form#15]
无法在ie浏览器使用  lib.js文件存在es6语法

**Comment by viewweiwu** [comment]
不考虑 ie

**Comment by weihuan1** [comment]
ie 10 和ie 11 都不支持应该把打包好的代码编译至es2015就可以了。

**Comment by viewweiwu** [comment]
没有考虑过 ie，如果需要使用可以直接拷贝 packages/iview-form.vue 到自己项目下使用，编译。
