### ISSUE TITLE
使用自定义整行(render)无法触发submit

### ISSUE THREAD

**Issue by nnnbgngau** [viewweiwu/iview-form#16]

**Comment by viewweiwu** [comment]
请给予例子

**Comment by nnnbgngau** [comment]
`
[
{
          key: "userName",
          render: (h, item, form) => <Input onInput={ (value) => form[item.key] = value } v-model={ this.userForm.username } prefix="md-contact" size="large" placeholder="请输入用户名/手机号/邮箱" />
        },
        {
          key: "password",
          render: (h, item, form) => <Input onInput={ (value) => form[item.key] = value } class="mt-2" v-model={ this.userForm.password } prefix="md-lock" size="large" placeholder="请输入密码" />
        }
]
`
在使用render参数渲染页面时，点击提交无法触发submit事件。如上代码

**Comment by viewweiwu** [comment]
@nbkSoo https://codepen.io/viewweiwu/pen/MGzBKM 请看这个例子
