### ISSUE TITLE
希望可以增加单条验证功能~~

### ISSUE THREAD

**Issue by nnnbgngau** [viewweiwu/iview-form#17]

**Comment by viewweiwu** [comment]
一直都有的呀，兄弟
https://codepen.io/viewweiwu/pen/QrJBLJ?editors=1010

**Comment by nnnbgngau** [comment]
有类似iview的validateField方法吗？比如只验证[https://codepen.io/viewweiwu/pen/QrJBLJ?editors=1010](url)例子中的用户名？

**Comment by viewweiwu** [comment]
好的，你一开是直接说这个例子，我就明白了，会马上考虑加上的

**Comment by viewweiwu** [comment]
@nbkSoo 已经更新了 validateField， method 调用，麻烦更新到 1.9.0

**Comment by nnnbgngau** [comment]
> @nbkSoo 已经更新了 validateField， method 调用，麻烦更新到 1.9.0

感谢，组件非常好用呢~
