### ISSUE TITLE
Hi，现在有没有根据上文，来判定下文是否展示的解决方案呢？

### ISSUE THREAD

**Issue by mqaaa** [viewweiwu/iview-form#18]

**Comment by viewweiwu** [comment]
可以的呀，用箭头函数
```
isShow: () => {
  // this
}
```

**Comment by mqaaa** [comment]
好的，我找时间看下，感谢

**Comment by mqaaa** [comment]
好像你说的这个我没懂，我看到表单只在初始化的时候更新一次～，之后表单里面的内容的变更，将不后面的内容。
你说的isShow是初始表单的时候的操作，
我是表单不清晰，我是想在同一表单内容，前点的被改了，后面的内容判定是否隐藏

**Comment by viewweiwu** [comment]
hi
回答的有点晚了，不知道现在是不是解决了问题
其实有例子的
https://codepen.io/viewweiwu/pen/erQjzY
