### ISSUE TITLE
设置grid属性后，字段isShow属性为true时，字段不显示了，但是布局占位还在

### ISSUE THREAD

**Issue by hitfzg** [viewweiwu/iview-form#4]
设置grid属性为2，字段isShow属性为true时，字段不显示了，但是布局占位还在
![image](https://user-images.githubusercontent.com/8349973/42263474-b38f36ae-7fa0-11e8-8205-7564d82db9cf.png)

**Comment by viewweiwu** [comment]
是的，如果你想要第一行占满的话，可以看下这个 demo
https://codepen.io/viewweiwu/pen/GGLBeX?editors=1010
