### ISSUE TITLE
请问如何给input绑定on-click等事件，目前好像只支持onInput事件

### ISSUE THREAD

**Issue by hitfzg** [viewweiwu/iview-form#6]
需求是在input后跟一个图标，需要捕获点击图标的事件，API里看好像只支持onInput，未找到如何绑定on-click等事件的说明。谢谢！

**Comment by viewweiwu** [comment]
你好！
清升级到 1.5.0 版本后便可以自己设置 on 事件了
请看 demo
https://codepen.io/viewweiwu/pen/EpKdKR?editors=1010

**Comment by viewweiwu** [comment]
感谢你的使用😀
