### ISSUE TITLE
render的这种渲染iViewForm方式对么，为啥渲染不出来呢

### ISSUE THREAD

**Issue by sanny1982** [viewweiwu/iview-form#7]
render: (h) => { 
                            return h('div',[
                              h('iViewForm',{
                                props:{
                                  formList:'formList1'
                                }}),
这是片断代码

**Comment by viewweiwu** [comment]
当然可以啦，看这里
https://codepen.io/viewweiwu/pen/EewwNa?editors=1010

**Comment by sanny1982** [comment]
iview的button按钮点击做的模态对话框调用formList貌似渲染不出来
  import iViewForm from 'iview-form'
  export default {
    name: 'devlist',
    components: {
      Tables,
      iViewForm
    },

----------------------
                   on: {
                      click: () => {
                        this.$Modal.confirm({
                          render: (h) => {
                            return h('div',[
                              h('i-switch',{
                                 props:{
                                   value:true      
                                 }}),
                              h('iview-form',{  //这里替替换成iViewForm也试了，没渲染出来呢
                                props: {
                                  formList: [
                                    {
                                      title: '输入框',
                                      type: 'input'
                                    }
                                  ]
                                }
                              }),
                            ])

![image](https://user-images.githubusercontent.com/40729578/45254322-020c3700-b3a9-11e8-9584-ad894314cbab.png)
![image](https://user-images.githubusercontent.com/40729578/45254359-747d1700-b3a9-11e8-8698-dab5c3eccdd3.png)
