### ISSUE TITLE
引入iview-form后 run build出错

### ISSUE THREAD

**Issue by hitfzg** [viewweiwu/iview-form#8]
npm run dev 正常，但是build的时候报错；
![image](https://user-images.githubusercontent.com/8349973/45251334-f6a01800-b376-11e8-8b75-c1416824e07f.png)

![image](https://user-images.githubusercontent.com/8349973/45251343-12a3b980-b377-11e8-85c7-152a0eec5ab3.png)

**Comment by viewweiwu** [comment]
你是如何使用的，代码拿出来看看

**Comment by hitfzg** [comment]
就是正常的引用，不过我是用的iview3.0，  后来根据报错修改了下源文件，可以打包成功了

![image](https://user-images.githubusercontent.com/8349973/45252215-89e04a00-b385-11e8-94ca-58b5531b45b9.png)

**Comment by hitfzg** [comment]
发现新版本还是有这个问题，是我配置有问题吗？

**Comment by viewweiwu** [comment]
你说的最新版是什么意思，vue-cli3 么
