### ISSUE TITLE
1.7在iview3.0下样式有问题

### ISSUE THREAD

**Issue by hitfzg** [viewweiwu/iview-form#9]
1.7下效果
![image](https://user-images.githubusercontent.com/8349973/45252819-a5e8e900-b38f-11e8-924e-a88941deb329.png)

1.6下效果
![image](https://user-images.githubusercontent.com/8349973/45252823-b26d4180-b38f-11e8-9c0d-bf297a22a933.png)

**Comment by viewweiwu** [comment]
确实有问题，等我查一下

**Comment by viewweiwu** [comment]
已修复 更新到 1.8.0
